start:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: auto_time_lapse

stop:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: auto_time_lapse
    render:
      required: false
      default: true
      selector:
        boolean:

render:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: auto_time_lapse

cancel:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: auto_time_lapse
